# Generated by Django 4.2.11 on 2026-03-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_activestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image_path',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
