# Generated by Django 4.2.11 on 2026-04-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artist_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_path',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
