# Generated by Django 4.2.11 on 2026-03-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_self_register', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Server settings',
                'verbose_name_plural': 'Server settings',
            },
        ),
    ]
