# Generated by Django 4.2.11 on 2026-04-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_serversettings'),
    ]

    operations = [
        # Core settings
        migrations.AddField(
            model_name='serversettings',
            name='secret_key',
            field=models.CharField(blank=True, help_text='Auto-generated Django SECRET_KEY', max_length=100),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='debug',
            field=models.BooleanField(default=False, help_text='Debug mode (never enable in production)'),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='server_name',
            field=models.CharField(default='Sonata', max_length=100),
        ),
        
        # CORS settings
        migrations.AddField(
            model_name='serversettings',
            name='cors_allowed_origins',
            field=models.TextField(
                blank=True,
                default='http://localhost:5173\nhttp://localhost:3000',
                help_text='One origin per line'
            ),
        ),
        
        # JWT settings
        migrations.AddField(
            model_name='serversettings',
            name='access_token_lifetime_minutes',
            field=models.IntegerField(default=1440, help_text='Default: 1440 (1 day)'),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='refresh_token_lifetime_days',
            field=models.IntegerField(default=7, help_text='Default: 7 days'),
        ),
        
        # Rate limiting
        migrations.AddField(
            model_name='serversettings',
            name='throttle_user_rate',
            field=models.CharField(default='1000/day', max_length=20),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='throttle_anon_rate',
            field=models.CharField(default='100/day', max_length=20),
        ),
        
        # LDAP settings
        migrations.AddField(
            model_name='serversettings',
            name='ldap_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ldap_server_uri',
            field=models.CharField(blank=True, default='ldap://localhost', max_length=255),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ldap_bind_dn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ldap_bind_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ldap_user_search_base',
            field=models.CharField(blank=True, default='ou=users,dc=example,dc=com', max_length=255),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ldap_user_search_filter',
            field=models.CharField(blank=True, default='(uid=%(user)s)', max_length=255),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ldap_attr_username',
            field=models.CharField(blank=True, default='uid', max_length=50),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ldap_attr_email',
            field=models.CharField(blank=True, default='mail', max_length=50),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ldap_attr_first_name',
            field=models.CharField(blank=True, default='givenName', max_length=50),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ldap_attr_last_name',
            field=models.CharField(blank=True, default='sn', max_length=50),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ldap_auto_create_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serversettings',
            name='ldap_default_role',
            field=models.CharField(
                choices=[('admin', 'Admin'), ('user', 'User')],
                default='user',
                max_length=10
            ),
        ),
        
        # Security
        migrations.AddField(
            model_name='serversettings',
            name='subsonic_encryption_key',
            field=models.CharField(blank=True, help_text='Key for encrypting Subsonic passwords', max_length=100),
        ),
    ]
